# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
   apt:
     packages:
     # Requirements for NetPyNE & libNeuroML
     - python-tk
     - python-lxml 
     - python-scipy 
     - python-matplotlib 
     - python-tornado
    
language: python
python: 3.6

virtualenv:
   system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_validatev1

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - cd neuroConstruct/generatedNeuroML2
    - ls -alt
    - omv list -V 
    
    
    

